'use strict';

/**
 * Craftera GodotAdapter (AP-7.3).
 *
 * Übersetzt ein GameProject (engine/project.js) in ein lauffähiges
 * Godot-Projekt auf der Platte:
 *   - `project.godot` (Projekt-Konfiguration, Main-Scene)
 *   - eine `.tscn`-Scene pro GameProject-Scene, mit einem Node pro Entity
 *
 * Verifikation (DoD): "Godot öffnet Projekt" — das erzeugte Projekt lässt
 * sich mit `godot --headless --path <dir> --quit` real öffnen.
 */

const fs = require('node:fs');
const path = require('node:path');

/**
 * Escaped einen String für Godot-Textformate (.tscn / project.godot).
 * Ersetzt Anführungszeichen und Backslashes.
 */
function godotEscape(value) {
  return String(value).replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

/**
 * Erzeugt den Inhalt einer `project.godot`-Datei.
 * @param {object} project - GameProject.
 * @param {string} mainScene - Relativer Pfad der Main-Scene (z.B. "scenes/scene_1.tscn").
 * @returns {string}
 */
function buildProjectGodot(project, mainScene) {
  const name = project.name || 'CrafteraGame';
  return `; Engine configuration file.
; Generated by Craftera GodotAdapter (AP-7.3).

config_version=5

[application]

config/name="${godotEscape(name)}"
run/main_scene="res://${mainScene}"
config/features=PackedStringArray("4.7")

[display]

window/size/viewport_width=1280
window/size/viewport_height=720
`;
}

/**
 * Erzeugt den Inhalt einer `.tscn`-Scene-Datei.
 * @param {object} scene - Scene-Objekt.
 * @param {object} project - GameProject (für Entities/Components).
 * @returns {string}
 */
function buildSceneTscn(scene, project) {
  const entities = project.entities.filter((e) => e.sceneId === scene.sceneId);
  const lines = [];
  lines.push('[gd_scene load_steps=2 format=3]');
  lines.push('');
  lines.push('[ext_resource type="Script" path="res://scripts/root.gd" id="1_root"]');
  lines.push('');
  lines.push('[node name="Root" type="Node2D"]');
  lines.push('script = ExtResource("1_root")');
  lines.push('');

  for (const entity of entities) {
    const t = entity.transform || { x: 0, y: 0, scale: 1, rotation: 0 };
    const nodeName = (entity.name || 'Entity').replace(/[^A-Za-z0-9_]/g, '_') || 'Entity';
    lines.push(`[node name="${godotEscape(nodeName)}" type="Node2D" parent="."]`);
    lines.push(`position = Vector2(${Number(t.x) || 0}, ${Number(t.y) || 0})`);
    if (Number(t.rotation)) {
      lines.push(`rotation = ${Number(t.rotation)}`);
    }
    if (Number(t.scale) && Number(t.scale) !== 1) {
      lines.push(`scale = Vector2(${Number(t.scale)}, ${Number(t.scale)})`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

/**
 * Erzeugt das Root-Skript, das jede Scene referenziert (damit Godot die
 * Scene ohne Fehler lädt).
 * @returns {string}
 */
function buildRootGd() {
  return `extends Node2D
# Generated by Craftera GodotAdapter (AP-7.3).
func _ready() -> void:
	pass
`;
}

/**
 * GodotAdapter — konkrete Implementierung des RuntimeAdapter-Interfaces (AP-7.2).
 */
class GodotAdapter {
  /**
   * @param {object} options - { outputDir }
   */
  constructor(options = {}) {
    this.outputDir = options.outputDir || path.join(process.cwd(), '.godot-build');
  }

  /**
   * Übersetzt ein GameProject in ein Godot-Projekt.
   * @param {object} project - GameProject-Objekt.
   * @returns {Promise<string>} Absoluter Pfad zum erzeugten Godot-Projekt.
   */
  async build(project) {
    if (!project || !Array.isArray(project.scenes)) {
      throw new Error('GodotAdapter.build: GameProject benötigt ein scenes-Array');
    }

    const out = this.outputDir;
    const scenesDir = path.join(out, 'scenes');
    const scriptsDir = path.join(out, 'scripts');
    fs.mkdirSync(scenesDir, { recursive: true });
    fs.mkdirSync(scriptsDir, { recursive: true });

    // Root-Skript schreiben.
    fs.writeFileSync(path.join(scriptsDir, 'root.gd'), buildRootGd(), 'utf8');

    // Szenen schreiben.
    const sceneFiles = [];
    for (const scene of project.scenes) {
      const fileName = `${scene.sceneId}.tscn`;
      fs.writeFileSync(path.join(scenesDir, fileName), buildSceneTscn(scene, project), 'utf8');
      sceneFiles.push(`scenes/${fileName}`);
    }

    // Main-Scene = erste Scene (oder Fallback).
    const mainScene = sceneFiles[0] || 'scenes/empty.tscn';
    if (sceneFiles.length === 0) {
      fs.writeFileSync(
        path.join(scenesDir, 'empty.tscn'),
        '[gd_scene load_steps=2 format=3]\n\n[ext_resource type="Script" path="res://scripts/root.gd" id="1_root"]\n\n[node name="Root" type="Node2D"]\nscript = ExtResource("1_root")\n',
        'utf8'
      );
    }

    // project.godot schreiben.
    fs.writeFileSync(path.join(out, 'project.godot'), buildProjectGodot(project, mainScene), 'utf8');

    return out;
  }

  /**
   * Startet eine Scene (AP-7.3: nur Projekt-Erzeugung; Play folgt in AP-7.9).
   */
  async play() {
    throw new Error('GodotAdapter.play: folgt in AP-7.9 (Play-Modus)');
  }

  async pause() {
    throw new Error('GodotAdapter.pause: folgt in AP-7.10');
  }

  async stop() {
    throw new Error('GodotAdapter.stop: folgt in AP-7.10');
  }
}

module.exports = {
  GodotAdapter,
  buildProjectGodot,
  buildSceneTscn,
  buildRootGd,
  godotEscape,
};
