'use strict';

/**
 * Craftera InputBridge (AP-7.7).
 *
 * Übersetzt InputActions eines GameProject in die Godot-InputMap.
 * Eine InputAction hat die Form:
 *   { actionId, name, keys }   // keys = Array von Godot-Key-Namen
 *   z.B. { actionId: 'act_1', name: 'move_left', keys: ['A', 'Left'] }
 *
 * Der Bridge erzeugt die `[input]`-Sektion für `project.godot`, die Godot
 * als InputMap lädt. Verifikation (DoD): "Input gemappt" — Godot lädt das
 * Projekt headless ohne Fehler und die Actions sind in der InputMap.
 */

const fs = require('node:fs');
const path = require('node:path');

/**
 * Erzeugt einen gültigen Godot-Action-Namen.
 * @param {string} name - z.B. 'move_left'.
 * @returns {string} z.B. 'move_left'.
 */
function actionNameFor(name) {
  const base = String(name || 'action').replace(/[^A-Za-z0-9_]/g, '_');
  return base || 'action';
}

/**
 * Erzeugt die `[input]`-Sektion für project.godot aus InputActions.
 * @param {Array<object>} actions - Array von { name, keys }.
 * @returns {string} Inhalt der [input]-Sektion (ohne Sektions-Header).
 */
function buildInputSection(actions) {
  const lines = [];
  for (const action of actions || []) {
    const name = actionNameFor(action.name);
    const keys = Array.isArray(action.keys) ? action.keys : [];
    lines.push(`input/${name}={
"deadzone": 0.5,
"events": [${keys.map((k) => `Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":-1,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":${keycodeFor(k)},"key_label":0,"unicode":0,"location":0,"echo":false,"script":null)`).join(', ')}]
}`);
  }
  return lines.join('\n');
}

/**
 * Mappt einen Godot-Key-Namen auf den physischen Keycode.
 * @param {string} key - z.B. 'A', 'Left', 'Space'.
 * @returns {number} Godot-Keycode.
 */
function keycodeFor(key) {
  const map = {
    A: 65, B: 66, C: 67, D: 68, E: 69, F: 70, G: 71, H: 72,
    I: 73, J: 74, K: 75, L: 76, M: 77, N: 78, O: 79, P: 80,
    Q: 81, R: 82, S: 83, T: 84, U: 85, V: 86, W: 87, X: 88,
    Y: 89, Z: 90,
    '0': 48, '1': 49, '2': 50, '3': 51, '4': 52, '5': 53,
    '6': 54, '7': 55, '8': 56, '9': 57,
    Space: 32, Enter: 4194309, Escape: 4194305, Tab: 4194306,
    Left: 4194319, Right: 4194321, Up: 4194320, Down: 4194322,
    Shift: 4194325, Control: 4194326, Alt: 4194327,
  };
  return map[String(key)] || 0;
}

/**
 * Erzeugt die vollständige project.godot-Datei inkl. InputMap.
 * @param {object} project - GameProject (mit `inputActions`-Array).
 * @param {string} mainScene - Relativer Pfad der Main-Scene.
 * @returns {string}
 */
function buildProjectGodotWithInput(project, mainScene) {
  const name = project.name || 'CrafteraGame';
  const inputSection = buildInputSection(project.inputActions || []);
  return `; Engine configuration file.
; Generated by Craftera InputBridge (AP-7.7).

config_version=5

[application]

config/name="${String(name).replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"
run/main_scene="res://${mainScene}"
config/features=PackedStringArray("4.7")

[display]

window/size/viewport_width=1280
window/size/viewport_height=720

[input]

${inputSection}
`;
}

/**
 * Übersetzt die InputActions eines GameProject in die InputMap und
 * schreibt die project.godot-Datei.
 * @param {object} project - GameProject.
 * @param {string} outputDir - Wurzel des Godot-Projekts.
 * @param {string} mainScene - Relativer Pfad der Main-Scene.
 * @returns {string} Absoluter Pfad der geschriebenen project.godot.
 */
function compileInput(project, outputDir, mainScene) {
  if (!project || !Array.isArray(project.inputActions)) {
    throw new Error('InputBridge.compileInput: GameProject benötigt ein inputActions-Array');
  }
  const content = buildProjectGodotWithInput(project, mainScene);
  const absPath = path.join(outputDir, 'project.godot');
  fs.mkdirSync(outputDir, { recursive: true });
  fs.writeFileSync(absPath, content, 'utf8');
  return path.resolve(absPath);
}

/**
 * InputBridge — übersetzt InputActions in die Godot-InputMap.
 */
class InputBridge {
  /**
   * @param {object} options - { outputDir }
   */
  constructor(options = {}) {
    this.outputDir = options.outputDir || path.join(process.cwd(), '.godot-build');
  }

  /**
   * Übersetzt die InputActions des Projekts in die InputMap.
   * @param {object} project - GameProject.
   * @param {string} mainScene - Relativer Pfad der Main-Scene.
   * @returns {Promise<string>} Pfad der geschriebenen project.godot.
   */
  async compile(project, mainScene) {
    return compileInput(project, this.outputDir, mainScene);
  }
}

// Statische Zugriffe (kompatibel mit Tests).
InputBridge.compileInput = compileInput;

module.exports = {
  InputBridge,
  compileInput,
  buildInputSection,
  buildProjectGodotWithInput,
  actionNameFor,
  keycodeFor,
};
