'use strict';

/**
 * Craftera ProjectBuilder (AP-7.8).
 *
 * Baut aus einem GameProject ein lauffähiges Godot-Projekt, indem er alle
 * Compiler orchestriert:
 *   - SceneCompiler  → Szenen (.tscn)
 *   - ResourceCompiler → Assets (res://assets/)
 *   - ScriptBridge   → Components als GDScript (res://scripts/)
 *   - InputBridge    → InputActions als InputMap (project.godot)
 *
 * Verifikation (DoD): "Godot startet" — das gebaute Projekt lässt sich mit
 * `godot --headless --path <dir> --quit` real starten (Exit 0).
 */

const fs = require('node:fs');
const path = require('node:path');

const { compileSceneToFile } = require('./sceneCompiler.js');
const { compileAssets } = require('./resourceCompiler.js');
const { compileComponents } = require('./scriptBridge.js');
const { buildProjectGodotWithInput } = require('./inputBridge.js');

/**
 * ProjectBuilder — baut ein GameProject zu einem lauffähigen Godot-Projekt.
 */
class ProjectBuilder {
  /**
   * @param {object} options - { outputDir }
   */
  constructor(options = {}) {
    this.outputDir = options.outputDir || path.join(process.cwd(), '.godot-build');
  }

  /**
   * Baut das GameProject in ein Godot-Projekt.
   * @param {object} project - GameProject.
   * @returns {Promise<object>} { outputDir, mainScene, scenes, assets, scripts }
   */
  async build(project) {
    if (!project || !Array.isArray(project.scenes)) {
      throw new Error('ProjectBuilder.build: GameProject benötigt ein scenes-Array');
    }

    const out = this.outputDir;
    const scenesDir = path.join(out, 'scenes');
    const scriptsDir = path.join(out, 'scripts');
    fs.mkdirSync(scenesDir, { recursive: true });
    fs.mkdirSync(scriptsDir, { recursive: true });

    // 1. Szenen kompilieren.
    const sceneFiles = [];
    for (const scene of project.scenes) {
      const fileName = `${scene.sceneId}.tscn`;
      compileSceneToFile(scene, project, path.join(scenesDir, fileName));
      sceneFiles.push(`scenes/${fileName}`);
    }

    // 2. Assets importieren.
    const assets = compileAssets(project, out);

    // 3. Components zu GDScript übersetzen.
    const scripts = compileComponents(project, out);

    // 4. Main-Scene bestimmen (erste Scene oder Fallback).
    const mainScene = sceneFiles[0] || 'scenes/empty.tscn';
    if (sceneFiles.length === 0) {
      fs.writeFileSync(
        path.join(scenesDir, 'empty.tscn'),
        '[gd_scene load_steps=2 format=3]\n\n[ext_resource type="Script" path="res://scripts/root.gd" id="1_root"]\n\n[node name="Root" type="Node2D"]\nscript = ExtResource("1_root")\n',
        'utf8'
      );
    }

    // 5. Root-Skript schreiben (falls nicht von ScriptBridge erzeugt).
    const rootGd = path.join(scriptsDir, 'root.gd');
    if (!fs.existsSync(rootGd)) {
      fs.writeFileSync(
        rootGd,
        'extends Node2D\n# Generated by Craftera ProjectBuilder (AP-7.8).\nfunc _ready() -> void:\n\tpass\n',
        'utf8'
      );
    }

    // 6. project.godot mit InputMap schreiben.
    const projectGodot = buildProjectGodotWithInput(project, mainScene);
    fs.writeFileSync(path.join(out, 'project.godot'), projectGodot, 'utf8');

    return {
      outputDir: out,
      mainScene,
      scenes: sceneFiles,
      assets,
      scripts,
    };
  }
}

module.exports = { ProjectBuilder };
