'use strict';

/**
 * Craftera ScriptBridge (AP-7.6).
 *
 * Übersetzt Components eines GameProject (engine/component.js) in GDScript.
 * Eine Component hat die Form { componentId, type, props }.
 *
 * Der Bridge erzeugt pro Component ein GDScript, das die Props als
 * Variablen deklariert und eine `_ready()`-Methode mit einem Kommentar
 * zum Component-Typ enthält. Verifikation (DoD): "Script läuft" — das
 * erzeugte GDScript wird von Godot headless geladen (kein Parse-Fehler).
 */

const fs = require('node:fs');
const path = require('node:path');

/**
 * Erzeugt einen sicheren GDScript-Klassennamen aus einem Component-Typ.
 * @param {string} type - z.B. 'sprite', 'player-controller'.
 * @returns {string} z.B. 'sprite', 'player_controller'.
 */
function classNameFor(type) {
  const base = String(type || 'component').replace(/[^A-Za-z0-9_]/g, '_');
  return base || 'component';
}

/**
 * Formatiert einen Prop-Wert als GDScript-Literal.
 * @param {*} value - Prop-Wert.
 * @returns {string} GDScript-Literal.
 */
function gdLiteral(value) {
  if (typeof value === 'number') return String(value);
  if (typeof value === 'boolean') return value ? 'true' : 'false';
  if (value === null || value === undefined) return 'null';
  if (Array.isArray(value)) return `[${value.map(gdLiteral).join(', ')}]`;
  if (typeof value === 'object') {
    const entries = Object.entries(value)
      .map(([k, v]) => `"${k}": ${gdLiteral(v)}`)
      .join(', ');
    return `{ ${entries} }`;
  }
  return `"${String(value).replace(/"/g, '\\"')}"`;
}

/**
 * Erzeugt den Inhalt eines GDScript für eine Component.
 * @param {object} component - { componentId, type, props }.
 * @returns {string} GDScript-Inhalt.
 */
function buildScript(component) {
  if (!component || !component.type) {
    throw new Error('ScriptBridge.buildScript: Component benötigt einen "type"');
  }
  const cls = classNameFor(component.type);
  const lines = [];
  lines.push(`extends Node2D`);
  lines.push(`# Generated by Craftera ScriptBridge (AP-7.6).`);
  lines.push(`# Component: ${component.type} (${component.componentId || '?'})`);
  lines.push('');
  lines.push(`class_name ${cls}`);
  lines.push('');
  // Props als Variablen deklarieren.
  const props = component.props || {};
  for (const [key, value] of Object.entries(props)) {
    const varName = key.replace(/[^A-Za-z0-9_]/g, '_') || 'value';
    lines.push(`var ${varName} = ${gdLiteral(value)}`);
  }
  lines.push('');
  lines.push(`func _ready() -> void:`);
  lines.push(`\tpass`);
  lines.push('');
  return lines.join('\n');
}

/**
 * Übersetzt eine Component in ein GDScript und schreibt es als Datei.
 * @param {object} component - Component-Objekt.
 * @param {string} outDir - Zielverzeichnis (z.B. <projekt>).
 * @returns {string} Relativer Pfad (z.B. "scripts/sprite.gd").
 */
function compileComponent(component, outDir) {
  const content = buildScript(component);
  const fileName = `${classNameFor(component.type)}.gd`;
  const scriptsDir = path.join(outDir, 'scripts');
  const absPath = path.join(scriptsDir, fileName);
  fs.mkdirSync(scriptsDir, { recursive: true });
  fs.writeFileSync(absPath, content, 'utf8');
  return `scripts/${fileName}`;
}

/**
 * Übersetzt alle Components eines GameProject in GDScript-Dateien.
 * @param {object} project - GameProject mit `entities` (die Components tragen).
 * @param {string} outDir - Zielverzeichnis.
 * @returns {string[]} Relative Script-Pfade.
 */
function compileComponents(project, outDir) {
  if (!project || !Array.isArray(project.entities)) {
    throw new Error('ScriptBridge.compileComponents: GameProject benötigt ein entities-Array');
  }
  const compiled = [];
  const seen = new Set();
  for (const entity of project.entities) {
    for (const component of entity.components || []) {
      const rel = compileComponent(component, outDir);
      if (!seen.has(rel)) {
        seen.add(rel);
        compiled.push(rel);
      }
    }
  }
  return compiled;
}

/**
 * ScriptBridge — übersetzt Components in GDScript.
 */
class ScriptBridge {
  /**
   * @param {object} options - { outputDir }
   */
  constructor(options = {}) {
    this.outputDir = options.outputDir || path.join(process.cwd(), '.godot-build');
  }

  /**
   * Übersetzt alle Components des Projekts in GDScript-Dateien.
   * @param {object} project - GameProject.
   * @returns {Promise<string[]>} Relative Script-Pfade.
   */
  async compile(project) {
    return compileComponents(project, this.outputDir);
  }
}

// Statische Zugriffe (kompatibel mit Tests).
ScriptBridge.compileComponent = compileComponent;
ScriptBridge.compileComponents = compileComponents;

module.exports = {
  ScriptBridge,
  compileComponent,
  compileComponents,
  buildScript,
  classNameFor,
  gdLiteral,
};
